### ISSUE TITLE
disabling forgets the last used ip address

### ISSUE THREAD

**Issue by amakare1** [theappbusiness/android-proxy-toggle#22]
I've installed the app on Pixel 4, Android 11 using the adb command 
The address text field doesn't appear to be editable.
I can change it using `adb shell settings put global http_proxy 192.168.0.110:8888`

After disabling and enabling it via the toggle, it changes the label text to an IP address of another value. example: `192.128.1.215` as seen in screenshot

sometimes when it's enabled, the address value in the app remains `192.128.1.215`, instead of showing `192.168.0.110`
when I tap on disable, the proxy remains enabled. I confirmed it by inspecting Charles app, which continued to display traffic from the device. 

![android-screenshot-13](https://user-images.githubusercontent.com/12764964/87447090-c43d5280-c5bf-11ea-9da5-a03f8837679a.png)

**Comment by fmontesino** [comment]
Hey @burgundine thanks for reporting this!
I seem to me that you're using a very old commit from the app on its early stages where the proxy was hardcoded to my local IP 😅 
If you're building the app directly from Android Studio, please make sure you have pulled the latest changes from the `main` branch. 
Alternatively, you can get the latest release from the download page [here](https://github.com/theappbusiness/android-proxy-toggle/releases/latest).

The UI should look something like this:
![image](https://user-images.githubusercontent.com/1481183/87521405-40956b80-c67c-11ea-8382-a743245c1823.png)

Let me know if you have any issues with this version.

Happy coding!
