### ISSUE TITLE
Old version under Releases

### ISSUE THREAD

**Issue by candeiasdan** [theappbusiness/android-proxy-toggle#24]
After installing the first version/releave, I have the app with no icon, and a main screen with "Enable" button. IP and port are automatically detected (not possible to configure)
Also, the widget is just a button to Enable the proxy.

The installed app has nothing to do with the one showing on Readme. Looks like under release, you have the first draft of the app.

**Comment by fmontesino** [comment]
Hey @candeiasdan I just downloaded the `.tar.gz` file from releases and installed on a fresh emulator and it looks as expected: 
<img src="https://user-images.githubusercontent.com/1481183/101808220-fc64a500-3b0d-11eb-8975-68b2b07235cd.png" width=300 />

Are you getting it from here?
https://github.com/theappbusiness/android-proxy-toggle/releases/tag/v1.0.0

If not, could you please point me to which `.apk` did you try to install?
I'll happily update them if required!

**Comment by candeiasdan** [comment]
@fmontesino unzipping the **tar.gz** I was able to install the app. 

If you download the source code (from the same page), and call `./installAndGrantPermission.sh`, you get a different version (mentioned above 👆 )

**Comment by fmontesino** [comment]
Oh, I see now! The source code is added automatically by GitHub when making a release, and the .apk at that time was wrong indeed.

Thanks for letting me know, I will try to amend it ASAP.

Enjoy the app!
