### ISSUE TITLE
URL support for proxy.pac 

### ISSUE THREAD

**Issue by ghost** [theappbusiness/android-proxy-toggle#27]
HI,

I would like to know if it was possible to set up an option or I could indicate a url proxy.pac so that all network traffic goes through the proxy.

Android 7, 8 and 9 are giving us errors (err proxy not supported) randomly, and your app would help us a lot.

Thank you for your reply. 

Best regards, 

Christophe

**Comment by kleinsenberg** [comment]
Sorry for the late reply. As far as I know we can't set a proxy pac file programatically but I also haven't used auto-config.
Sounds like an interesting feature but I'm not sure we'll have time to look into it soon. 

Feel free to open a pull request if you decide to implement it yourself!
