### ISSUE TITLE
feature request Could you add support to set user and password ?

### ISSUE THREAD

**Issue by rsanjuan87** [theappbusiness/android-proxy-toggle#33]
feature request
Could you add support to set user and password ?

**Comment by instasck** [comment]
it will be nice !

**Comment by kleinsenberg** [comment]
Hi there, we had a similar request here a while ago https://github.com/theappbusiness/android-proxy-toggle/issues/32

Unfortunately there's not further development planned on this at the moment. We're more than happy to accept PRs though!
