### ISSUE TITLE
(Question) Does The programm need a rooted device?

### ISSUE THREAD

**Issue by wenjucktes01** [theappbusiness/android-proxy-toggle#34]
Most Programs like that need an rooted Phone or Tablet. My Questio or issue is, does it need an rooted device?

**Comment by geftimov** [comment]
@wenjucktes01 No it doesn't require a rooted device.

**Comment by wenjucktes01** [comment]
In my place wie have a proxy with authentication via username and password is this a problem?

**Comment by geftimov** [comment]
It is a problem.
[android-proxy-toggle](https://github.com/theappbusiness/android-proxy-toggle) doesn't support username/password proxy authentication.
It is possible to be implemented but we don't have much time to do that.
If you want to give it a go and contribute to this repo you are more than welcome.

**Comment by wenjucktes01** [comment]
Well its pretty hard to find a program wich can do it. Thx for your invteatio but i have to pass. I am at the moment an student and donßt have much time and my only skills i have are some in Java but they are not the best.
