### ISSUE TITLE
cannot proxy all apps 

### ISSUE THREAD

**Issue by qi-cai** [theappbusiness/android-proxy-toggle#38]
my issue is only a small number of apps can be proxied in the HarmonyOS 3.0 . I'm sure the proxy toggle is being run effectively, but many apps are not being proxied by it or going through its tunnels. may you update the app and fix this issue?

**Comment by geftimov** [comment]
Hey, @qi-cai you are probably referring to apps with `Certification pinning`. 
This repository doesn't work with specific apps - it just sets Android-wide specific proxy so all the network requests go through. Maybe give an example or sample so we can see what we can do?

**Comment by qi-cai** [comment]
@geftimov thanks for your reply. According to its description, the app should be a global proxy, which means that all traffic should pass through it when it is active. But this was not the case when I used it. I'm a noob so I don't know if these apps used https or not, or if it's some other issue.  I have also tested some other http proxy apps(in the HarmonyOS 3.0 ) they can work normally, but they are killed after using for a while when working in the background.  I just tested it yesterday on my usual apps (which are all downloaded from the Huawei App Market) for example "bilibili" was not being proxied properly.

**Comment by albakhtari** [comment]
I'm facing the same issue on Android 11.
I used my OWASP ZAP http request editor as the proxy, and everything running in the browser worked as expected and the traffic was caught by the proxy, while all other apps weren't able to connect to the internet.

**EDIT:** I added that same proxy with the android system settings and the same thing happened, so it's not a problem with the app itself, rather with how android is dealing with proxies...
