### ISSUE TITLE
Proxy still exists after disconnecting

### ISSUE THREAD

**Issue by hadis91** [theappbusiness/android-proxy-toggle#43]
Proxy still exists after disconnecting

**Comment by geftimov** [comment]
Yes, this unfortunately is a caveat that we know about.
We even added it to the ReadMe.md file : [be-careful-when-uninstalling-the-app](https://github.com/theappbusiness/android-proxy-toggle?tab=readme-ov-file#be-careful-when-uninstalling-the-app)
